name: Publish to WinGet

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  publish-winget:
    runs-on: windows-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Submit to Microsoft Winget
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: noclue.vtui
          # We MUST use zip because cargo-dist uploads zips, not raw exes
          installers-regex: '\.zip$' 
          token: ${{ secrets.WINGET_TOKEN }}